/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Empresa;
import javax.swing.ImageIcon;

/**
 *
 * @author jvall
 */
public class vtnBoletaPasaje extends javax.swing.JFrame {

    private Empresa emp;
    /**
     * Creates new form vntBoletaPasaje
     * @param emp
     * @param dni
     * @param nombres
     * @param ruta
     * @param asiento
     * @param piso
     * @param precio
     */
    public vtnBoletaPasaje(Empresa emp,String dni,String nombres,String ruta, String asiento, String piso, String precio,String placa,String conductor,String recepcionista,String fecha, String hora) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
        this.emp = emp;
        llenarDatos(dni,nombres,ruta,asiento,piso,precio,placa,conductor,recepcionista,fecha,hora);
    }

    public void llenarDatos(String DNI, String nomb,String ru,String asient,String pis,String prec,String plac,String conduc,String recep,String f, String h){
        ruc.setText(emp.getRuc());
        dni.setText(DNI);
        nombres.setText(nomb);
        ruta.setText(ru);
        asiento.setText(asient);
        piso.setText(pis);
        precio.setText(prec);
        recepcionista.setText(recep);
        Fecha.setText(f);
        Hora.setText(h);
        conductor.setText(conduc);
        placa.setText(plac);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ruc = new javax.swing.JTextField();
        recepcionista = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Hora = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ruta = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        asiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        piso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        conductor = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("BOLETA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 807, 10));

        ruc.setEditable(false);
        jPanel1.add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 101, 107, -1));

        recepcionista.setEditable(false);
        jPanel1.add(recepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 101, 110, -1));

        Fecha.setEditable(false);
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 101, 70, -1));

        jLabel2.setText("Ruc:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 103, -1, 20));

        jLabel3.setText("Recepcionista:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 105, -1, -1));

        jLabel4.setText("Fecha y hora:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 105, -1, -1));

        Hora.setEditable(false);
        jPanel1.add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 101, 70, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 807, -1));

        ruta.setEditable(false);
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 110, -1));

        dni.setEditable(false);
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 110, -1));

        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 167, -1, -1));

        nombres.setEditable(false);
        jPanel1.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, -1));

        jLabel6.setText("Nombres:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel7.setText("Origen - Destino");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel8.setText("N° Asiento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 171, -1, -1));

        asiento.setEditable(false);
        jPanel1.add(asiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 47, -1));

        jLabel9.setText("N° Piso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        piso.setEditable(false);
        jPanel1.add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 47, -1));

        jLabel10.setText("Precio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        precio.setEditable(false);
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 60, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 291, 807, 30));

        jLabel11.setText("Datos del Bus");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel12.setText("Nombre del Conductor:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel13.setText("Placa del bus:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        conductor.setEditable(false);
        jPanel1.add(conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, -1));

        placa.setEditable(false);
        jPanel1.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 651, 490, 0));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 83, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 391, 807, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo2.0.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 250, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnBoletaPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnBoletaPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnBoletaPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnBoletaPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnBoletaPasaje(null,null,null,null,null,null,null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fecha;
    private javax.swing.JTextField Hora;
    private javax.swing.JTextField asiento;
    private javax.swing.JTextField conductor;
    private javax.swing.JTextField dni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField piso;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField recepcionista;
    private javax.swing.JTextField ruc;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables
}
