/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Empresa;
import clases.ItinerarioFurgon;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jvall
 */
public class vtnItinerarioEncomienda extends javax.swing.JFrame {

    Empresa emp;
    /**
     * Creates new form vtnitinerarioFurgon
     */
    public vtnItinerarioEncomienda(Empresa emp1) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
        emp = emp1;
        tablaItinerarioFurgon.setModel(emp.mostrarDatosItFurgon());
        llenarCombox();
    }

    public double excepcionCosto(){
        boolean flag;
        double monto=0;
        String cadena = costo.getText();
        do{
            try{
                monto = Double.parseDouble(cadena);
                flag = false;
                costo.setBackground(Color.white);
            } catch(NumberFormatException e){
                costo.setBackground(Color.red);
                cadena = JOptionPane.showInputDialog("Ingrese un monto numerico");
                costo.setText(cadena);
                flag = true;
            }
        } while(flag);
        return monto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaItinerarioFurgon = new javax.swing.JTable();
        ruta = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        comboConductor = new javax.swing.JComboBox<>();
        comboPlaca = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Itinerario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setText("Ruta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 78, -1, -1));

        jLabel3.setText("Conductor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 125, -1, -1));

        jLabel4.setText("Placa del Furgon:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 167, -1, -1));

        jLabel5.setText("Costo por Kg:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 216, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 266, -1, 43));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 266, -1, 43));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 266, 91, 43));

        tablaItinerarioFurgon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ruta", "Conductor", "Placa furgon", "Precio por Kg"
            }
        ));
        tablaItinerarioFurgon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaItinerarioFurgonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaItinerarioFurgon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 327, 490, 193));
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 74, 155, -1));
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 208, 87, -1));

        comboConductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jPanel1.add(comboConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 120, 192, -1));

        comboPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jPanel1.add(comboPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 155, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 526, 76, 44));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo2.0peque.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 160, 60));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Encomiendas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarItinerario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        modificarItinerario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tablaItinerarioFurgonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaItinerarioFurgonMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaItinerarioFurgon.rowAtPoint(evt.getPoint());
        mostrarTabla(filaSeleccionada);
    }//GEN-LAST:event_tablaItinerarioFurgonMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarItinerario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void llenarCombox(){
        ArrayList<String> datos = new ArrayList<>();
        datos = emp.conductores('f');
        for(int i=0;i<datos.size();i++){
            comboConductor.addItem(datos.get(i));
        }
        comboConductor.setSelectedItem(null);
        datos = emp.placas('f');
        for(int j=0;j<datos.size();j++){
            comboPlaca.addItem(datos.get(j));
        }
        comboPlaca.setSelectedItem(null);
    }
    
    public void agregarItinerario(){
        ItinerarioFurgon iF = new ItinerarioFurgon();
        iF.setRuta(ruta.getText());
        int indiceCond = comboConductor.getSelectedIndex();
        iF.setConductorDNI(comboConductor.getItemAt(indiceCond));
        int indicePlaca = comboPlaca.getSelectedIndex();
        iF.setPlacaFurgon(comboPlaca.getItemAt(indicePlaca));
        iF.setPrecioPorKilo(excepcionCosto());
        emp.agregarItinerario_Furgon(iF);
        limpiarCampos();
        tablaItinerarioFurgon.setModel(emp.mostrarDatosItFurgon());
    }
    
    public void modificarItinerario(){
        ItinerarioFurgon iF = new ItinerarioFurgon();
        iF.setRuta(ruta.getText());
        int indiceCond = comboConductor.getSelectedIndex();
        iF.setConductorDNI(comboConductor.getItemAt(indiceCond));
        int indicePlaca = comboPlaca.getSelectedIndex();
        iF.setPlacaFurgon(comboPlaca.getItemAt(indicePlaca));
        iF.setPrecioPorKilo(Double.parseDouble(costo.getText()));
        emp.actualizarItinerarioFurgon(iF, tablaItinerarioFurgon);
        limpiarCampos();
        tablaItinerarioFurgon.setModel(emp.mostrarDatosItFurgon());
    }
    
    public void mostrarTabla(int filaSeleccionada){
        ruta.setText(tablaItinerarioFurgon.getValueAt(filaSeleccionada, 1).toString());
        comboConductor.setSelectedItem(tablaItinerarioFurgon.getValueAt(filaSeleccionada, 2).toString());
        comboPlaca.setSelectedItem(tablaItinerarioFurgon.getValueAt(filaSeleccionada, 3).toString());
        costo.setText(tablaItinerarioFurgon.getValueAt(filaSeleccionada, 4).toString());
    }
    
    public void eliminarItinerario(){
        emp.eliminarDatosItinerarioFurgon(tablaItinerarioFurgon);
        limpiarCampos();
        tablaItinerarioFurgon.setModel(emp.mostrarDatosItFurgon());
    }
    
    public void limpiarCampos(){
        ruta.setText("");
        comboConductor.setSelectedItem(null);
        comboPlaca.setSelectedItem(null);
        costo.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnItinerarioEncomienda(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboConductor;
    private javax.swing.JComboBox<String> comboPlaca;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta;
    private javax.swing.JTable tablaItinerarioFurgon;
    // End of variables declaration//GEN-END:variables
}
