/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Empresa;
import clases.ItinerarioBus;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jvall
 */
public class vtnItinerarioViajes extends javax.swing.JFrame {
    
    Empresa emp1;
    /**
     * Creates new form vtnItinerario
     */
    public vtnItinerarioViajes(Empresa emp) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
        emp1 = emp;
        tablaDestinos.setModel(emp1.mostrarDatosItBus());
        llenarCombox();
    }

    public double excepcionCosto1(){
        boolean flag;
        double sueldo=0;
        String cadena = txtCosto1.getText();
        do{
            try{
                sueldo = Double.parseDouble(cadena);
                flag = false;
                txtCosto1.setBackground(Color.white);
            } catch(NumberFormatException e){
                txtCosto1.setBackground(Color.red);
                cadena = JOptionPane.showInputDialog("Ingrese un monto numerico");
                txtCosto1.setText(cadena);
                flag = true;
            }
        } while(flag);
        return sueldo;
    }
    public double excepcionCosto2(){
        boolean flag;
        double monto=0;
        String cadena = txtCosto2.getText();
        do{
            try{
                monto = Double.parseDouble(cadena);
                flag = false;
                txtCosto2.setBackground(Color.white);
            } catch(NumberFormatException e){
                txtCosto2.setBackground(Color.red);
                cadena = JOptionPane.showInputDialog("Ingrese un monto numerico");
                txtCosto2.setText(cadena);
                flag = true;
            }
        } while(flag);
        return monto;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDestinos = new javax.swing.JTable();
        txtRuta = new javax.swing.JTextField();
        txtHorarioSalida = new javax.swing.JTextField();
        txtCosto1 = new javax.swing.JTextField();
        txtCosto2 = new javax.swing.JTextField();
        btnAgregarItinerarioViajes = new javax.swing.JButton();
        btnModificarItinerarioViajes = new javax.swing.JButton();
        btnElimniarItinerarioViajes = new javax.swing.JButton();
        btnVolverIV = new javax.swing.JButton();
        select_conductor = new javax.swing.JComboBox<>();
        comboPlaca = new javax.swing.JComboBox<>();
        comboTerramoza = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Itinerario de viajes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setText("Ruta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel3.setText("Conductor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel4.setText("Placa del bus:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel5.setText("Hora de salida:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel6.setText("Costo primer piso:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel7.setText("Costo segundo piso:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        tablaDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destino", "Conductor", "Placa", "Hora salida", "Costo 1° piso", "Costo 2° piso"
            }
        ));
        tablaDestinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDestinosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDestinos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 520, 160));

        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, -1));
        jPanel1.add(txtHorarioSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 178, -1));
        jPanel1.add(txtCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 110, -1));
        jPanel1.add(txtCosto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 110, -1));

        btnAgregarItinerarioViajes.setText("Agregar");
        btnAgregarItinerarioViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarItinerarioViajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarItinerarioViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 90, 40));

        btnModificarItinerarioViajes.setText("Modificar");
        btnModificarItinerarioViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarItinerarioViajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarItinerarioViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 90, 40));

        btnElimniarItinerarioViajes.setText("Eliminar");
        btnElimniarItinerarioViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimniarItinerarioViajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnElimniarItinerarioViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 80, 40));

        btnVolverIV.setText("Volver");
        btnVolverIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIVActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 80, 50));

        select_conductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jPanel1.add(select_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 220, -1));

        comboPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jPanel1.add(comboPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 180, -1));

        comboTerramoza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jPanel1.add(comboTerramoza, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, -1));

        jLabel8.setText("Terramoza:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo2.0peque.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaActionPerformed

    private void btnVolverIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIVActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverIVActionPerformed

    private void btnAgregarItinerarioViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarItinerarioViajesActionPerformed
        // TODO add your handling code here:
        agregarItinerario();
    }//GEN-LAST:event_btnAgregarItinerarioViajesActionPerformed

    private void btnElimniarItinerarioViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimniarItinerarioViajesActionPerformed
        // TODO add your handling code here:
        eliminarItinerario();
    }//GEN-LAST:event_btnElimniarItinerarioViajesActionPerformed

    private void btnModificarItinerarioViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarItinerarioViajesActionPerformed
        // TODO add your handling code here:
        modificarItinerario();
    }//GEN-LAST:event_btnModificarItinerarioViajesActionPerformed

    private void tablaDestinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDestinosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaDestinos.rowAtPoint(evt.getPoint());
        mostrarTabla(filaSeleccionada);
    }//GEN-LAST:event_tablaDestinosMouseClicked

    public void llenarCombox(){
        ArrayList<String> datos;
        datos = emp1.conductores('b');
        for(int i=0;i<datos.size();i++){
            select_conductor.addItem(datos.get(i));
        }
        select_conductor.setSelectedItem(null);
        datos = emp1.placas('b');
        for(int j=0;j<datos.size();j++){
            comboPlaca.addItem(datos.get(j));
        }
        comboPlaca.setSelectedItem(null);
        datos = emp1.terramozas();
        for(int k=0;k<datos.size();k++){
            comboTerramoza.addItem(datos.get(k));
        }
        comboTerramoza.setSelectedItem(null);
    }
    
    public void agregarItinerario(){
        ItinerarioBus itBus;
        itBus = insertarItineariosBus();
        emp1.agregarItinerario_buses(itBus);
        mostrarItinerarioBus();
        limpiarCajas();
    }
    
    public void eliminarItinerario(){
        String idItBus = getIdItinerarioBus();
        emp1.eliminarDatosItBus(idItBus);
        mostrarItinerarioBus();
        limpiarCajas();
    }
    
    public void modificarItinerario(){
        ItinerarioBus itBus;
        itBus = insertarItineariosBus();
        String idItBus = getIdItinerarioBus();
        emp1.actualizarDatosItBus(idItBus, itBus);
        mostrarItinerarioBus();
        limpiarCajas();
    }
    
    public void mostrarTabla(int filaSeleccionada){
        txtRuta.setText(tablaDestinos.getValueAt(filaSeleccionada, 1).toString());
        txtHorarioSalida.setText(tablaDestinos.getValueAt(filaSeleccionada, 4).toString());
        txtCosto2.setText(tablaDestinos.getValueAt(filaSeleccionada, 6).toString());
        txtCosto1.setText(tablaDestinos.getValueAt(filaSeleccionada, 7).toString());
        select_conductor.setSelectedItem(tablaDestinos.getValueAt(filaSeleccionada, 2));
        comboPlaca.setSelectedItem(tablaDestinos.getValueAt(filaSeleccionada, 3).toString());
        comboTerramoza.setSelectedItem(tablaDestinos.getValueAt(filaSeleccionada, 5));
    }
    
    public ItinerarioBus insertarItineariosBus() {
        ItinerarioBus itBus = new ItinerarioBus();
        itBus.setRuta(txtRuta.getText());
        int conductorSeleccionado = select_conductor.getSelectedIndex();
        itBus.setConductorDNI(select_conductor.getItemAt(conductorSeleccionado));
        int placaSeleccionada = comboPlaca.getSelectedIndex();
        itBus.setPlacaBus(comboPlaca.getItemAt(placaSeleccionada));
        itBus.setHorarioSalida(txtHorarioSalida.getText());
        int terramozaSeleccionada = comboTerramoza.getSelectedIndex();
        itBus.setTerramozaDNI(comboTerramoza.getItemAt(terramozaSeleccionada));
        itBus.setCostoPrimerPiso(excepcionCosto1());
        itBus.setCostoSegundoPiso(excepcionCosto2());
        return itBus;
    }
    public void mostrarItinerarioBus() {
        tablaDestinos.setModel(emp1.mostrarDatosItBus());
    }
    public void limpiarCajas() {
        txtRuta.setText("");
        txtHorarioSalida.setText("");
        txtCosto1.setText("");
        txtCosto2.setText("");
        select_conductor.setSelectedItem(null);
        comboPlaca.setSelectedItem(null);
        comboTerramoza.setSelectedItem(null);
    }
    public String getIdItinerarioBus() {
        int filaSeleccionada = tablaDestinos.getSelectedRow();
        String dao = (String)tablaDestinos.getValueAt(filaSeleccionada, 0);
        return dao;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnItinerarioViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vtnItinerarioViajes(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItinerarioViajes;
    private javax.swing.JButton btnElimniarItinerarioViajes;
    private javax.swing.JButton btnModificarItinerarioViajes;
    private javax.swing.JButton btnVolverIV;
    private javax.swing.JComboBox<String> comboPlaca;
    private javax.swing.JComboBox<String> comboTerramoza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> select_conductor;
    private javax.swing.JTable tablaDestinos;
    private javax.swing.JTextField txtCosto1;
    private javax.swing.JTextField txtCosto2;
    private javax.swing.JTextField txtHorarioSalida;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
