/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Agencia;
import clases.Cliente;
import clases.Empresa;
import clases.ItinerarioBus;
import clases.VentaPasaje;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jvall
 */
public class vtnVentaPasajes extends javax.swing.JFrame {
    private Empresa emp;
    private String r; //ruta
    private String h; //horario
    private ItinerarioBus itBus;
    private String recepcionista;
    private String fecha;
    private String hora;
    private Agencia agen;
    /**
     * Creates new form vtnVentaPasajes
     * @param emp1
     * @param nombre
     */
    public vtnVentaPasajes(Empresa emp1,String nombre) {
        emp = emp1;
        recepcionista=nombre;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());;
        agen = new Agencia(emp1);
        hora = "";
        fecha = "";
        llenarRutas();

    }
    
    public void validarDatosNumericos(java.awt.event.KeyEvent evento2){
        if((evento2.getKeyChar() >= 48 && evento2.getKeyChar() <= 57)){
            if(txtDniCliente.getText().length()>8){
                JOptionPane.showMessageDialog(this, "Solo se admiten 9 digitos","Informacion", JOptionPane.INFORMATION_MESSAGE);
                txtDniCliente.setText(txtDniCliente.getText().substring(0, 9));
            }
        }
        else if(!(evento2.getKeyCode()==KeyEvent.VK_BACK_SPACE||evento2.getKeyCode()==KeyEvent.VK_LEFT||evento2.getKeyCode()==KeyEvent.VK_RIGHT
                ||evento2.getKeyCode()==KeyEvent.VK_ENTER)){
            JOptionPane.showMessageDialog(this, "Solo se admiten caracteres numericos","Error", JOptionPane.ERROR_MESSAGE);
            int ind = txtDniCliente.getText().length()-1;
            if(!(txtDniCliente.getText().charAt(ind)>='0'&& txtDniCliente.getText().charAt(ind) <= '9'))
               txtDniCliente.setText(txtDniCliente.getText().substring(0, ind));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboRutas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboHorario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtNameCliente = new javax.swing.JTextField();
        txtSexCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnLlenarDatos = new javax.swing.JButton();
        btnVerAsientos = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DNI: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 46, -1));

        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyPressed(evt);
            }
        });
        jPanel1.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 90, -1));

        jLabel3.setText("Ruta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        comboRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRutasActionPerformed(evt);
            }
        });
        jPanel1.add(comboRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, -1));

        jLabel5.setText("Asiento: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        txtAsiento.setEditable(false);
        jPanel1.add(txtAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 49, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Venta de Pasajes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnRegistrar.setText("Registrar pasaje");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, 40));

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, 40));

        jLabel8.setText("Precio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        txtPrecio.setEditable(false);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 59, -1));

        jLabel9.setText("Piso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        txtPiso.setEditable(false);
        jPanel1.add(txtPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 40, -1));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel7.setText("Horario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        comboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(comboHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 120, -1));

        jLabel10.setText("Nombres:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtNameCliente.setEditable(false);
        jPanel1.add(txtNameCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 90, -1));

        txtSexCliente.setEditable(false);
        jPanel1.add(txtSexCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 90, -1));

        jLabel11.setText("Sexo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        btnLlenarDatos.setText("llenar Datos");
        btnLlenarDatos.setEnabled(false);
        btnLlenarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLlenarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        btnVerAsientos.setText("Ver asientos");
        btnVerAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAsientosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo2.0peque.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_btnValidarActionPerformed

    private void comboRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRutasActionPerformed
        // TODO add your handling code here:
        llenarHorarios();
    }//GEN-LAST:event_comboRutasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        registrarVenta();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLlenarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarDatosActionPerformed
        // TODO add your handling code here:
        llenarCampos();
    }//GEN-LAST:event_btnLlenarDatosActionPerformed

    private void comboHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHorarioActionPerformed
        // TODO add your handling code here:
        getItinerarioBus();
    }//GEN-LAST:event_comboHorarioActionPerformed

    private void btnVerAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsientosActionPerformed
        // TODO add your handling code here:
        verAsientosDisponibles();
    }//GEN-LAST:event_btnVerAsientosActionPerformed

    private void txtDniClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyPressed
        // TODO add your handling code here:
        validarDatosNumericos(evt);
    }//GEN-LAST:event_txtDniClienteKeyPressed

    public void llenarRutas(){
        ArrayList<String> rutas = emp.rutas('b');
        for(int i=0;i<rutas.size();i++){
            comboRutas.addItem(rutas.get(i));
        }
        comboRutas.setSelectedItem(null);
        comboHorario.addItem("Seleccione ruta");
    }
    
    public void verAsientosDisponibles(){
        ArrayList<Integer> asientos = emp.obtenerAsientosBus(itBus.getPlacaBus());
        vtnAsientosBus vAsient = new vtnAsientosBus(emp,itBus.getPlacaBus(),asientos);
        vAsient.setVisible(true);
        btnLlenarDatos.setEnabled(true);
        btnVerAsientos.setEnabled(false);
    }
    
    public void getItinerarioBus(){
        int indiceRuta = comboRutas.getSelectedIndex();
        r = comboRutas.getItemAt(indiceRuta);
        int indiceHorario = comboHorario.getSelectedIndex();
        h = comboHorario.getItemAt(indiceHorario);
        itBus = emp.obtenerItinerario(r, h);
    }
    public void registrarVenta(){
        llenarVentaPasaje();
        vtnBoletaPasaje vBp = new vtnBoletaPasaje(emp,txtDniCliente.getText(),txtNameCliente.getText(),r,txtAsiento.getText(),txtPiso.getText(),txtPrecio.getText(),itBus.getPlacaBus(),itBus.getConductorDNI(),recepcionista,fecha,hora);
        vBp.setVisible(true);
        limpiarTextos();
        btnValidar.setEnabled(true);
    }
    
    public String getHora(){
        Calendar date = Calendar.getInstance();
        int ho,min,seg;
        ho = date.get(Calendar.HOUR_OF_DAY);
        min = date.get(Calendar.MINUTE);
        seg = date.get(Calendar.SECOND);
        return ho+":"+min+":"+seg;
    }
    
    public void llenarVentaPasaje(){
        Date fechad = new Date();
        VentaPasaje ventPas = new VentaPasaje();
        ventPas.setNumAsiento(Integer.parseInt(txtAsiento.getText()));
        ventPas.setPiso(Integer.parseInt(txtPiso.getText()));
        ventPas.setClienteDNI(txtDniCliente.getText());
        ventPas.setRuta(r);
        ventPas.setHorarioSalida(h);
        ventPas.setMontoTotalPagado(Double.parseDouble(txtPrecio.getText()));
        fecha = new SimpleDateFormat("dd-MM-yyyy").format(fechad);
        ventPas.setFechaPago(fecha);
        hora = getHora();
        ventPas.setHoraPago(hora);
        agen.llenarVentas(ventPas);
    }
    public void llenarCampos(){
        ArrayList<Integer> datos = emp.obtenerDatosAsiento(itBus.getPlacaBus());
        txtAsiento.setText(String.valueOf(datos.get(0)));
        txtPiso.setText(String.valueOf(datos.get(1)));
        if(Integer.parseInt(txtPiso.getText())==1) 
            txtPrecio.setText(String.valueOf(itBus.getCostoPrimerPiso()));
        else
            txtPrecio.setText(String.valueOf(itBus.getCostoSegundoPiso()));
        btnRegistrar.setEnabled(true);
    }
    
    public void buscarCliente(){
        if(emp.buscarClienteDni(txtDniCliente.getText())){
            Cliente client = emp.getCliente();
            txtNameCliente.setText(client.getNombres());
            txtSexCliente.setText(client.getSexo());
            btnValidar.setEnabled(false);
        }
        else{
            vtnRegistroCliente vRe = new vtnRegistroCliente(txtDniCliente.getText(),emp);
            vRe.setVisible(true);
        }
    }
    
    public void llenarHorarios(){
        ArrayList horarios;
        String rutaBuscar;
        int indice;
        indice = comboRutas.getSelectedIndex(); 
        rutaBuscar = comboRutas.getItemAt(indice);
        horarios = emp.horarios(rutaBuscar);
        if(horarios!=null){
            comboHorario.removeAllItems();
            for(int j=0;j<horarios.size();j++){
                comboHorario.addItem(horarios.get(j).toString());
            }
        }
    }
    public void limpiarTextos(){
        txtDniCliente.setText("");
        txtNameCliente.setText("");
        txtSexCliente.setText("");
        txtAsiento.setText("");
        txtPiso.setText("");
        txtPrecio.setText("");
        comboRutas.setSelectedItem(null);
        comboHorario.setSelectedItem(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnVentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnVentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnVentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnVentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vtnVentaPasajes(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLlenarDatos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVerAsientos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboHorario;
    private javax.swing.JComboBox<String> comboRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtNameCliente;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSexCliente;
    // End of variables declaration//GEN-END:variables
}
